language: node_js
before_install:
  - npm install -g npm@~1.4.18
node_js:
  - "0.10"
before_script:
  - npm install git+https://github.com/node-red/node-red.git
  - export NODE_RED_HOME=`pwd`/node_modules/node-red
  - (cd $NODE_RED_HOME ; npm install nock )